graph TD
    A[Samuel Stargardtzer<br>b.c. 1819, d. 12 Oct 1879] -->|Married| B[Rosalie Kammlitzer]
    A --> C[Marie Stargardtzer]
    C -->|Married| D[Simon Gottfeld<br>b. 27 Jun 1863, d. 9 Dec 1937]
    D --> E[Fannie Gottfeld<br>b.c. 1857, d. Apr 1900]
    E -->|Married| F[Moritz Grossman<br>b. 27 Aug 1887]
    F --> G[Sam Grossman<br>b. 24 Aug 1888, d. Jan 1962]
    F --> H[Paul Grossman<br>b. 11 Apr 1890]
    F --> I[Rose Grossman<br>b. 3 Feb 1892]
    F --> J[Gertrude Grossman<br>b. 26 Oct 1848, d. 2 Feb 1912]
    
    K[Dora Epstein<br>b.c. 1863, d.c. 1930] -->|Married| L[Louis Epstein<br>b.c. 1860, d. 1942]
    L --> M[Henry Epstein<br>b. 23 Apr 1883]
    L --> N[Rose Epstein<br>b.c. 1886]
    N -->|Married| O[Jack Silverman<br>b.b. 1883]
    O --> P[Irene<br>b.c. 1908, d. 1 Aug 1957]
    L --> Q[Frank Epstein<br>b. 17/22 Jan 1891, d. 1 Aug 1957]
    Q -->|Married| R[Wanda]
    
    S[Arthur (Adolf) Epstein<br>b. 1896] -->|Married| T[Daisy McQueen]
    S --> U[Clara Chaplin]
    U -->|Married| V[Mary Anne McElgunn<br>b. Feb 23, 1897]
    S --> W[Edwin Epstein]
    S --> X[Paul Epstein]
    S --> Y[Herbert (Talus Taylor) Epstein<br>b. Sep 17, 1929]
    S --> Z[Arlene Epstein<br>b. Nov 17, 1930]
    Z -->|Married| AA[William Thomas Fell<br>b. 1925]
    AA --> AB[Lila Anne<br>b. Sep 14, 1950]
    
    AC[David Epstein<br>b.c. 1899] -->|Married| AD[Kate]
    AC --> AE[Marcia]
    AE -->|Married| AF[Edith]
    AC --> AG[Henrietta Epstein<br>b. Dec 21, 1901, d. Mar 1986]
    AG -->|Married| AH[Jerry Simon]
    AC --> AI[Marion Epstein<br>b.c. 1904, d. Dec 15, 1994]
    AI -->|Married| AJ[Henry Kreisman<br>b.c. 1930, d. Dec 7, 2007]
    AJ --> AK[Sue Kreisman]
    AK -->|Married| AL[Robert Siegel]
    AL --> AM[Mark Siegel]
    AL --> AN[Ann Siegel]
    
    AO[Pauline Stargardter<br>b.c. 1855, d. 17 Jan 1913] -->|Married| AP[Moritz Bukofzer<br>b.c. 1881, d. 5 Apr 1917]
    AP --> AQ[Emma Ernestine<br>b.c. 3 Sep 1881]
    AQ -->|Married| AR[Morris Bokker<br>b.c. 1873]
    AR --> AS[Sadie Bokker<br>b. 26 Jan 1904]
