graph TD
    A[Shia Halpern<br>b.c., d. Feb 16, 1953] -->|Married| B[Surafieiga (Rose Halpern or Halber?)]
    A --> C[Rudella (Rose Halpern or Halber?)<br>b.c. 1871, d. 1930]
    C --> D[Moischko (Morris) Muntlack<br>b.c. 1861, d. 1974/1976?]
    D --> E[David Muntlack<br>b.c. 1890?]
    E --> F[Harold Muntlack<br>b.c. 1897, d. Mar 1934]
    E --> G[Sam Muntlack (Montauk)<br>b.c. 1897, d. Oct 6, 1984]
    G -->|Married| H[Sadie Epstein<br>b. Nov 13, 1918]
    G --> I[Ernest Montauk<br>b. Jun 30, 1918]
    I --> J[Susan Montauk<br>b. Dec 14, 1943]
    J -->|Married| K[Stan Loeb]
    J --> L[Ben Coulter]
    L -->|Married| M[Amber (ward)]
    I --> N[Lance Montauk<br>b. Apr 22, 1956]
    N -->|Married| O[Krystyna Brzeziecki Montauk<br>b. Nov 3, 1981]
    N --> P[Dobromir Yoni Montauk<br>b. Nov 14, 1984]
    N --> Q[Basia Beres<br>b. Mar 25, 2010]
    N --> R[Kajetan Yoni Montauk<br>b. Dec 14, 1992]
    G --> S[Clare Lynn Feldman<br>b. Jun 30, 1918]
