graph TD
    title[Family Tree]
    class title title
    %% Stargardtzer Family
    A["Samuel Stargardtzer
    b.c. 1819, d. 12 Oct 1879"] -->|Married| B["Rosalie Kammlitzer"]
    A --> C["Marie Stargardtzer"]
    C -->|Married| D["Simon Gottfeld
    b. 27 Jun 1863, d. 9 Dec 1937"]
    D --> E["Fannie Gottfeld
    b.c. 1857, d. Apr 1900"]
    E -->|Married| F["Moritz Grossman
    b. 27 Aug 1887"]
    F --> G["Sam Grossman
    b. 24 Aug 1888, d. Jan 1962"]
    F --> H["Paul Grossman
    b. 11 Apr 1890"]
    F --> I["Rose Grossman
    b. 3 Feb 1892"]
    F --> J["Gertrude Grossman
    b. 26 Oct 1848, d. 2 Feb 1912"]
    
    %% Epstein Family
    K["Dora Epstein
    b.c. 1863, d.c. 1930"] -->|Married| L["Louis Epstein
    b.c. 1860, d. 1942"]
    L --> M["Henry Epstein
    b. 23 Apr 1883"]
    L --> N["Rose Epstein
    b.c. 1886"]
    N -->|Married| O["Jack Silverman
    b.b. 1883"]
    O --> P["Irene
    b.c. 1908, d. 1 Aug 1957"]
    L --> Q["Frank Epstein
    b. 17/22 Jan 1891, d. 1 Aug 1957"]
    Q -->|Married| R["Wanda"]
    L --> S["Arthur (Adolf) Epstein
    b. 1896"]
    S -->|Married| T["Daisy McQueen"]
    S --> U["Clara Chaplin"]
    U -->|Married| V["Mary Anne McElgunn
    b. Feb 23, 1897"]
    S --> W["Edwin Epstein"]
    S --> X["Paul Epstein"]
    S --> Y["Herbert (Talus Taylor) Epstein
    b. Sep 17, 1929"]
    S --> Z["Arlene Epstein
    b. Nov 17, 1930"]
    Z -->|Married| AA["William Thomas Fell
    b. 1925"]
    AA --> AB["Lila Anne
    b. Sep 14, 1950"]
    L --> AC["David Epstein
    b.c. 1899"]
    AC -->|Married| AD["Kate"]
    AC --> AE["Marcia"]
    AE -->|Married| AF["Edith"]
    AC --> AG["Henrietta Epstein
    b. Dec 21, 1901, d. Mar 1986"]
    AG -->|Married| AH["Jerry Simon"]
    AC --> AI["Marion Epstein
    b.c. 1904, d. Dec 15, 1994"]
    AI -->|Married| AJ["Henry Kreisman
    b.c. 1930, d. Dec 7, 2007"]
    AJ --> AK["Sue Kreisman"]
    AK -->|Married| AL["Robert Siegel"]
    AL --> AM["Mark Siegel"]
    AL --> AN["Ann Siegel"]
    
    %% Stargardter-Bukofzer Family
    A --> AO["Pauline Stargardter
    b.c. 1855, d. 17 Jan 1913"]
    AO -->|Married| AP["Moritz Bukofzer
    b.c. 1881, d. 5 Apr 1917"]
    AP --> AQ["Emma Ernestine
    b.c. 3 Sep 1881"]
    AQ -->|Married| AR["Morris Bokker
    b.c. 1873"]
    AR --> AS["Sadie Bokker
    b. 26 Jan 1904"]
    
    %% Halpern Family
    HA["Shia Halpern
    b.c., d. Feb 16, 1953"] -->|Married| HB["Surafieiga (Rose Halpern or Halber?)"]
    HA --> HC["Rudella (Rose Halpern or Halber?)
    b.c. 1871, d. 1930"]
    HC --> HD["Moischko (Morris) Muntlack
    b.c. 1861, d. 1974/1976?"]
    HD --> HE["David Muntlack
    b.c. 1890?"]
    HE --> HF["Harold Muntlack
    b.c. 1897, d. Mar 1934"]
    HE --> HG["Sam Muntlack (Montauk)
    b.c. 1897, d. Oct 6, 1984"]
    HG -->|Married| HH["Sadie Epstein
    b. Nov 13, 1918"]
    %% Connect to Epstein family via invisible edge
    HH ~~~ L
    HG --> HI["Ernest Montauk
    b. Jul 13, 1918, d. 1980"]
    
    %% Brill-Montauk Connection
    BA["Samuel Brill
    b.c."] -->|Married| BB["Fannie (Flora) Ehrenberg
    b.c."]
    BA --> BC["Celia Brill
    b.c. 1896, d. May 1972"]
    BC -->|Married| BD["Harry Feldman
    b. 1876, d. May 1972"]
    
    %% Finkleroth-Feldman Connection
    FA["Max Finkleroth
    b.c."] -->|Married| FB["Rachel Finkleroth
    b.c., d. 1963"]
    %% Connect to Harry Feldman
    FB --> BD
    
    %% Combined Feldman-Montauk family
    BC --> BE["Clare Feldman
    b. Jun 30, 1920, d. 1963"]
    %% Connect Ernest Montauk
    BE -->|Married| HI
    HI --> BF["Susan Montauk
    b. Dec 14, 1943"]
    BF -->|Married| BG["Stan Loeb"]
    BF --> BH["Ben Coulter"]
    BH -->|Married| BI["Amber (ward)"]
    HI --> BJ["Lance Montauk
    b. Oct 8, 1947, d. Sep 18, 1980"]
    BJ -->|Married| BK["Krystyna
    b. Apr 22, 1956"]
    BJ --> BL["Dobromir Montauk
    b. Nov 3, 1981"]
    BL -->|Married| BM["Barbara Beres
    b. Nov 14, 1984"]
    BJ --> BN["Kajetan Montauk
    b. Mar 25, 2010"]
    BJ --> BO["Iliana Montauk
    b. Dec 24, 1982"]
    
    %% Feldman-Roisen Branch
    BC --> BP["Harriet Feldman
    b. Sep 13, 1930, d. May 5, 2003"]
    BP -->|Married| BQ["William Roisen
    b. May 26, 1926"]
    BQ --> BR["Kathi Roisen
    b. Mar 5, 1956"]
    BR -->|Married| BS["Howard Goldenberg
    b. Dec 6, 1949"]
    BS --> BT["Sam Goldenberg
    b. Feb 24, 1988"]
    BS --> BU["Joshua Goldenberg
    b. Oct 15, 1990"]
    BQ --> BV["Jill Roisen
    b. Dec 30, 1959"]
    
    %% Brill-Haber Branch
    BA --> BW["Tillie Brill
    b.c. 1891, d. Sep 1941"]
    BW -->|Married| BX["Jack Haber
    b.c. 1885"]
    BX --> BY["Sam Haber
    b. 1914"]
    BY -->|Married| BZ["Dottie
    b. Dec 25, 1919, d. Feb 2, 2002"]
    BX --> CA["Murray Haber"]
    CA -->|Married| CB["Shirley"]
    BX --> CC["Jeanne Haber
    b. 1942"]
    CC -->|Married| CD["Lou Abramson"]
    CC -->|Married| CE["Jake Gomez"]
    BX --> CF["Tina Marie Haber
    b.c. 1928"]
    BX --> CG["Paul & Herbie Haber
    b.c. 1928"]
    
    %% Feldman-Ressler Branch
    BD --> CH["Ruth"]
    CH -->|Married| CI["Sam Ressler"]
    CI --> CJ["Jeffrey Ressler
    b. May 29, 1943"]
    CJ --> CK["Jason Ressler
    b. Jul 4, 1970"]
    CK -->|Married| CL["Vivien Lindenfeld
    b. Oct 27, 1968"]
    CJ --> CM["Gary Ressler
    b. Apr 11, 1974"]
    CJ --> CN["Jordan Ressler
    b. 1981, d. Nov 17, 2004"]
    CI --> CO["Allen Ressler
    b. Jun 8, 1945"]
    CO -->|Married| CP["Ann Nicklason
    b. Feb 15"]
    CI --> CQ["Sophia Ressler"]
    CI --> CR["Samara Ressler
    b. Mar 10, 1980"]
    CR -->|Married| CS["Elizabeth"]
    CR --> CT["Justin Ressler
    b. Apr 1983, d. 1997"]
    CR --> CU["Jessica Ressler"]
    CR --> CV["Samuel Jay Ressler"]

    %% Apply styling
    classDef deceased fill:#f9f9f9,stroke:#ccc,color:#999
    classDef living fill:#e0f7fa,stroke:#4dd0e1,color:#00838f
    classDef title fill:none,stroke:none,font-weight:bold,font-size:20px
    
    %% Mark deceased individuals
    class A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,HA,HB,HC,HD,HE,HF,HG,HH,HI,BA,BB,BC,BD,BE,BP,BJ,CN,CT deceased
    
    %% Mark living individuals
    class BF,BG,BH,BI,BK,BL,BM,BN,BO,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CO,CP,CQ,CR,CS,CU,CV living