graph TD
    title[Family Tree]
    class title title
    
    %% Stargardtzer Family
    A["Samuel Stargardtzer
    b.c. 1819, d. 12 Oct 1879"] <-->|Married| B["Rosalie Kammlitzer"]
    C["Marie Stargardtzer (Gottfeld)
    b. 27 Jun 1863, d. 9 Dec 1937"] --> A
    C --> B
    C <-->|Married| D["Simon Gottfeld"]
    E["Fannie Gottfeld (Grossman)
    b.c. 1857, d. Apr 1900"] --> C
    E --> D
    E <-->|Married| F["Moritz Grossman
    b. 27 Aug 1887"]
    G["Sam Grossman
    b. 24 Aug 1888, d. Jan 1962"] --> E
    G --> F
    H["Paul Grossman
    b. 11 Apr 1890"] --> E
    H --> F
    I["Rose Grossman
    b. 3 Feb 1892"] --> E
    I --> F
    J["Gertrude Grossman
    b. 26 Oct 1848, d. 2 Feb 1912"] --> E
    J --> F
    
    %% Stargardtzer-Lehnstul Family
    EL["Ernestine Stargardter (Lehnstul)
    b.c. 1860, d. Jul 1913"] --> A
    EL --> B
    EL <-->|Married| ML["Moritz Lehnstul
    b.b. 1852, d. Jul 1913"]
    SL["Samuel Lehnstul
    b. 11 Aug 1882, d. Bef 1910"] --> EL
    SL --> ML
    RL["Rose Lehnstul (Goldstein)
    b. 23 Apr 1884, d. Mar 1970"] --> EL
    RL --> ML
    LL["Louis Lehnstul"] --> EL
    LL --> ML
    ETL["Ethel Lehnstul"] --> EL
    ETL --> ML
    ABL["Adele Beatrice Lehnstul (Tunick)
    b. 15 Mar 1915, d. 17 Feb 1981"] --> EL
    ABL --> ML
    
    %% Bukofzer Family Connection
    PS["Pauline Stargardter (Bukofzer)
    b.c. 1855, d. 17 Jan 1913"] --> A
    PS --> B
    PS <-->|Married| MB["Moritz Bukofzer
    b.c. 1858, d. 5 Apr 1917"]
    EB["Emma (Ernestine) Bukofzer"] --> PS
    EB --> MB
    DB["David Bukofzer
    b. 8 Jul 1883, d. 10 Jan 1915"] --> PS
    DB --> MB
    RBk["Rose Bukofzer
    b. 1885, d. Oct 1913"] --> PS
    RBk --> MB
    FB["Frances (Franziska) Bukofzer (La Beau)
    b. 7 Nov 1887"] --> PS
    FB --> MB
    JB["John Jack Bukofzer
    b. 12 Jul 1890, d. Bef 1910"] --> PS
    JB --> MB
    RgB["Reginey Bukofzer
    b. 17 Dec 1893, d. Oct 1973"] --> PS
    RgB --> MB
    
    %% Epstein Family
    K["Dora Stargardt (Epstein)
    b.c. Sep 1863, d.c. 1930"] <-->|Married| L["Louis Epstein
    b.c. Aug 1860, d. 1942"]
    M["Henry Epstein
    b. 23 Apr 1883"] --> K
    M --> L
    N["Rose Epstein (Silverman)
    b.c. 1886"] --> K
    N --> L
    N <-->|Married| O["Jack Silverman
    b.b. 1883"]
    P["Irene Silverman
    b.c. 1908, d. 1 Aug 1957"] --> N
    P --> O
    Q["Frank Epstein
    b. 17/22 Jan 1891, d. 1 Aug 1957"] --> K
    Q --> L
    Q <-->|Married| R["Wanda Epstein"]
    S["Arthur (Adolf) Epstein
    b. 1896"] --> K
    S --> L
    S <-->|Married| T["Daisy McQueen"]
    U["Clara Chaplin"] --> S
    U --> T
    U <-->|Married| V["Mary Anne McElgunn
    b. 23 Feb 1897"]
    W["Edwin Epstein"] --> S
    W --> T
    X["Paul Epstein"] --> S
    X --> T
    Y["Herbert (Talus Taylor) Epstein
    b. 17 Sep 1929"] --> S
    Y --> T
    Z["Arlene Epstein (Fell)
    b. 17 Nov 1930"] --> S
    Z --> T
    Z <-->|Married| AA["William Thomas Fell
    b. 1925"]
    AB["Lila Anne Fell
    b. 14 Sep 1950"] --> Z
    AB --> AA
    AC["David Epstein
    b.c. 1899"] --> K
    AC --> L
    AC <-->|Married| AD["Kate"]
    AE["Marcia"] --> AC
    AE --> AD
    AE <-->|Married| AF["Edith"]
    AG["Henrietta Epstein (Simon)
    b. 21 Dec 1901, d. Mar 1986"] --> AC
    AG --> AD
    AG <-->|Married| AH["Jerry Simon"]
    AI["Marion Epstein (Kreisman)
    b.c. 1904, d. 15 Dec 1994"] --> AC
    AI --> AD
    AI <-->|Married| AJ["Henry Kreisman
    b.c. 1930, d. 7 Dec 2007"]
    AK["Sue Kreisman (Siegel)"] --> AI
    AK --> AJ
    AK <-->|Married| AL["Robert Siegel"]
    AM["Mark Siegel"] --> AK
    AM --> AL
    AN["Ann Siegel"] --> AK
    AN --> AL
    
    %% Halpern Family
    HA["Shia Halpern"] <-->|Married| HB["Surafeiga (Rose Halpern or Halber?)
    b.c. 1871, d. 1930"]
    HC["Rudella (Rose Halpern or Halber?)
    b.c. 1861, d. 1930"] --> HA
    HC --> HB
    HD["Moischko (Morris) Muntlack
    b.c. 1861, d. 1974/1976?"] --> HC
    HE["David Muntlack
    b.c. 1890?"] --> HD
    HF["Harold Muntlack
    b. 1897, d. Mar 1934"] --> HE
    HG["Sam Muntlack (Montauk)
    b. Nov 1897, d. 6 Oct 1984"] --> HE
    HG <-->|Married| SE["Sadie Epstein (Montauk)
    b. 30 Nov 1897, d. 8 Oct 1984"]
    %% Connect to Epstein family via invisible edge
    SE ~~~ L
    HI["Ernest Montauk
    b. 13 Jul 1918"] --> HG
    HI --> SE
    
    %% Brill-Montauk Connection
    BA["Samuel Brill
    b.c."] <-->|Married| BB["Fannie (Flora) Ehrenberg
    b.c."]
    BC["Celia Brill (Feldman)
    b.c. 1896, d. May 1972"] --> BA
    BC --> BB
    BC <-->|Married| BD["Harry Feldman
    b.c. 1886, d. May 1972"]
    
    %% Finkleroth-Feldman Connection
    FA["Max Finkleroth
    b.c., d. 1963"] <-->|Married| FB["Rachel Finkleroth
    b.c."]
    %% Connect to Harry Feldman
    BD --> FA
    BD --> FB
    
    %% Combined Feldman-Montauk family
    BE["Clare Feldman (Montauk)
    b. 30 Jun 1920, d. 1963"] --> BC
    BE --> BD
    %% Connect Ernest Montauk
    BE <-->|Married| HI
    BF["Susan Montauk
    b. 14 Dec 1943"] --> BE
    BF --> HI
    BF <-->|Married| BG["Stan Loeb"]
    BH["Ben Coulter"] --> BF
    BH --> BG
    BH <-->|Married| BI["Amber (ward)"]
    BJ["Lance Montauk
    b. 8 Oct 1947"] --> BE
    BJ --> HI
    BJ <-->|Married| BK["Krystyna
    b. 22 Apr 1956"]
    BL["Dobromir Montauk
    b. 3 Nov 1981"] --> BJ
    BL --> BK
    BL <-->|Married| BM["Barbara Beres
    b. 14 Nov 1984"]
    KM["Kajetan Montauk
    b. 25 Mar 2010"] --> BL
    KM --> BM
    BO["Iliana Montauk
    b. 24 Dec 1982"] --> BJ
    BO --> BK
    
    %% Feldman-Roisen Branch
    BP["Harriet Feldman (Roisen)
    b. 13 Sep 1930, d. 5 May 2003"] --> BC
    BP --> BD
    BP <-->|Married| BQ["William Roisen
    b. 26 May 1926"]
    BR["Kathi Roisen (Goldenberg)
    b. 5 Mar 1956"] --> BP
    BR --> BQ
    BR <-->|Married| BS["Howard Goldenberg
    b. 6 Dec 1949"]
    BT["Sam Goldenberg
    b. 24 Feb 1988"] --> BR
    BT --> BS
    BU["Joshua Goldenberg
    b. 15 Oct 1990"] --> BR
    BU --> BS
    BV["Jill Roisen
    b. 30 Dec 1959"] --> BP
    BV --> BQ
    
    %% Brill-Haber Branch
    BW["Tillie Brill (Haber)
    b.c. 1891, d. Sep 1941"] --> BA
    BW --> BB
    BW <-->|Married| BX["Jack Haber
    b.c. 1885"]
    BY["Sam Haber
    b. 1914"] --> BW
    BY --> BX
    BY <-->|Married| BZ["Dottie
    b. 25 Dec 1919, d. 2 Feb 2002"]
    CA["Murray Haber"] --> BW
    CA --> BX
    CA <-->|Married| CB["Shirley"]
    CC["Jeanne Haber (Abramson/Gomez)
    b. 1942"] --> BW
    CC --> BX
    CC <-->|Married| CD["Lou Abramson"]
    CC <-->|Married| CE["Jake Gomez"]
    CF["Tina Marie Haber
    b.c. 1928"] --> BW
    CF --> BX
    CG["Paul & Herbie Haber
    b.c. 1928"] --> BW
    CG --> BX
    
    %% Feldman-Ressler Branch
    CH["Ruth Feldman (Ressler)"] --> BC
    CH --> BD
    CH <-->|Married| CI["Sam Ressler"]
    CJ["Jeffrey Ressler
    b. 29 May 1943"] --> CH
    CJ --> CI
    CK["Jason Ressler
    b. 4 Jul 1970"] --> CJ
    CK <-->|Married| CL["Vivien Lindenfeld
    b. 27 Oct 1969"]
    CM["Gary Ressler
    b. 11 Apr 1974"] --> CJ
    CN["Jordan Ressler
    b. 1981, d. 17 Nov 2004"] --> CJ
    CO["Allen Ressler
    b. 8 Jun 1945"] --> CH
    CO --> CI
    CO <-->|Married| CP["Ann Nicklason
    b. 15 Feb"]
    CQ["Sophia Ressler"] --> CH
    CQ --> CI
    CR["Samara Ressler
    b. 10 Mar 1980"] --> CH
    CR --> CI
    CR <-->|Married| CS["Elizabeth"]
    CT["Justin Ressler
    b. Apr 1983, d. 1997"] --> CR
    CT --> CS
    CU["Jessica Ressler"] --> CR
    CU --> CS
    CV["Samuel Jay Ressler"] --> CR
    CV --> CS

    %% Apply styling
    classDef deceased fill:#f9f9f9,stroke:#ccc,color:#999
    classDef living fill:#e0f7fa,stroke:#4dd0e1,color:#00838f
    classDef title fill:none,stroke:none,font-weight:bold,font-size:20px
    
    %% Mark deceased individuals
    class A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,PS,MB,DB,RBk,FB,JB,RgB,EB,HA,HB,HC,HD,HE,HF,HG,SE,BA,BB,BC,BD,BE,BP,CN,CT,EL,ML,SL,RL,LL,ETL,ABL deceased
    
    %% Mark living individuals
    class BF,BG,BH,BI,BJ,BK,BL,BM,KM,BO,BQ,BR,BS,BT,BU,BV,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CO,CP,CQ,CR,CS,CU,CV living